FROM bitnami/python:3.9.18-debian-11-r46

RUN apt-get update && \
    apt-get install -y libgmp-dev

COPY /network/requirements-net.txt /app
COPY /dataLayer/requirements.txt /app

RUN git clone https://github.com/libp2p/py-libp2p

WORKDIR /app

RUN mkdir -p /app/dbs

RUN pip install --upgrade pip setuptools

RUN cd py-libp2p && pip install -e .[dev] && cd ..

RUN pip install -r requirements-net.txt

RUN pip install -r requirements.txt

EXPOSE 8000

EXPOSE 8001

EXPOSE 5000

COPY /dataLayer/Store.py /app
COPY /dataLayer/AuthKey.py /app
COPY /dataLayer/Entities.py /app

COPY /network/main.py /app

CMD ["python","main.py", "--port", "8001", "-d", "/ip4/172.17.0.3/tcp/8000/p2p/QmQpMLzbsBMAWGQ6aQWqhWDQNMrcUCJyTjvQkrZT8SeyWX"]