FROM bitnami/python:3.9.18-debian-11-r46

COPY requirements-api.txt /app

WORKDIR /app

RUN pip install -r requirements-api.txt

EXPOSE 4000

EXPOSE 5000

COPY api.py /app

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "4000"]